name: Bug report 🐛
description: Report errors or unexpected behavior 🤔
labels: Needs-Triage
body:
- type: checkboxes
  attributes:
    label: Prerequisites
    options:
    - label: Write a descriptive title.
      required: true
    - label: Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/SentinelARConverter/)
      required: true
    - label: Search the existing issues.
      required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: >
      List of steps, sample code, failing test or link to a project that reproduces the behavior.
      Make sure you place a stack trace inside a code (```) block to avoid linking unrelated issues.
    placeholder: >
      I am experiencing a problem with X.
      I think Y should be happening but Z is actually happening.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    render: console
    placeholder: |
      PS>  Convert-SentinelARArmToYaml -Filename "C:\Temp\MyRule.json" -OutFile "C:\Temp\MyRule.yaml"
      I expected this line to create Myrule.yaml based on Myrule.json.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behavior
    render: console
    placeholder: |
      PS> Convert-SentinelARArmToYaml -Filename "C:\Temp\MyRule.json" -OutFile "C:\Temp\MyRule.yaml"
      Exception: /Users/user/.local/share/powershell/Modules/SentinelARConverter/1.1.2/public/Convert-SentinelARArmToYaml.ps1:60
      Line |
        60 |                  throw "File not found"
           |                  ~~~~~~~~~~~~~~~~~~~~~~
           | File not found
      
  validations:
    required: true
- type: textarea
  attributes:
    label: Error details
    description: Paste verbatim output from `Get-Error` if PowerShell return an error.
    render: console
    placeholder: PS> Get-Error
- type: textarea
  attributes:
    label: Environment data
    description: Paste verbatim output from `$PSVersionTable` below.
    render: powershell
    placeholder: PS> $PSVersionTable
  validations:
    required: true
- type: textarea
  attributes:
    label: Visuals
    description: >
      Please upload images or animations that can be used to reproduce issues in the area below.
      Try the [Steps Recorder](https://support.microsoft.com/en-us/windows/record-steps-to-reproduce-a-problem-46582a9b-620f-2e36-00c9-04e25d784e47)
      on Windows or [Screenshot](https://support.apple.com/en-us/HT208721) on macOS.
